package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarouselItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarouselItemAllPropertiesEquals(CarouselItem expected, CarouselItem actual) {
        assertCarouselItemAutoGeneratedPropertiesEquals(expected, actual);
        assertCarouselItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarouselItemAllUpdatablePropertiesEquals(CarouselItem expected, CarouselItem actual) {
        assertCarouselItemUpdatableFieldsEquals(expected, actual);
        assertCarouselItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarouselItemAutoGeneratedPropertiesEquals(CarouselItem expected, CarouselItem actual) {
        assertThat(actual)
            .as("Verify CarouselItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarouselItemUpdatableFieldsEquals(CarouselItem expected, CarouselItem actual) {
        assertThat(actual)
            .as("Verify CarouselItem relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarouselItemUpdatableRelationshipsEquals(CarouselItem expected, CarouselItem actual) {
        assertThat(actual)
            .as("Verify CarouselItem relationships")
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getConfiguracion()).as("check configuracion").isEqualTo(expected.getConfiguracion()));
    }
}
