package com.hotel.app.domain;

import static com.hotel.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaHabitacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaHabitacionAllPropertiesEquals(CategoriaHabitacion expected, CategoriaHabitacion actual) {
        assertCategoriaHabitacionAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaHabitacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaHabitacionAllUpdatablePropertiesEquals(CategoriaHabitacion expected, CategoriaHabitacion actual) {
        assertCategoriaHabitacionUpdatableFieldsEquals(expected, actual);
        assertCategoriaHabitacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaHabitacionAutoGeneratedPropertiesEquals(CategoriaHabitacion expected, CategoriaHabitacion actual) {
        assertThat(actual)
            .as("Verify CategoriaHabitacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaHabitacionUpdatableFieldsEquals(CategoriaHabitacion expected, CategoriaHabitacion actual) {
        assertThat(actual)
            .as("Verify CategoriaHabitacion relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getPrecioBase())
                    .as("check precioBase")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioBase())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaHabitacionUpdatableRelationshipsEquals(CategoriaHabitacion expected, CategoriaHabitacion actual) {
        // empty method
    }
}
