package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckInCheckOutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAllPropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertCheckInCheckOutAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckInCheckOutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAllUpdatablePropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertCheckInCheckOutUpdatableFieldsEquals(expected, actual);
        assertCheckInCheckOutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAutoGeneratedPropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutUpdatableFieldsEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut relevant properties")
            .satisfies(a -> assertThat(a.getFechaCheckIn()).as("check fechaCheckIn").isEqualTo(expected.getFechaCheckIn()))
            .satisfies(a -> assertThat(a.getHoraCheckIn()).as("check horaCheckIn").isEqualTo(expected.getHoraCheckIn()))
            .satisfies(a -> assertThat(a.getFechaCheckOut()).as("check fechaCheckOut").isEqualTo(expected.getFechaCheckOut()))
            .satisfies(a -> assertThat(a.getHoraCheckOut()).as("check horaCheckOut").isEqualTo(expected.getHoraCheckOut()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutUpdatableRelationshipsEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut relationships")
            .satisfies(a -> assertThat(a.getReservaDetalle()).as("check reservaDetalle").isEqualTo(expected.getReservaDetalle()));
    }
}
