package com.hotel.app.domain;

import static com.hotel.app.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CheckInCheckOutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAllPropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertCheckInCheckOutAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckInCheckOutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAllUpdatablePropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertCheckInCheckOutUpdatableFieldsEquals(expected, actual);
        assertCheckInCheckOutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutAutoGeneratedPropertiesEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutUpdatableFieldsEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaHoraCheckIn())
                    .as("check fechaHoraCheckIn")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaHoraCheckIn())
            )
            .satisfies(a ->
                assertThat(a.getFechaHoraCheckOut())
                    .as("check fechaHoraCheckOut")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaHoraCheckOut())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInCheckOutUpdatableRelationshipsEquals(CheckInCheckOut expected, CheckInCheckOut actual) {
        assertThat(actual)
            .as("Verify CheckInCheckOut relationships")
            .satisfies(a -> assertThat(a.getReservaDetalle()).as("check reservaDetalle").isEqualTo(expected.getReservaDetalle()));
    }
}
