package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfiguracionSistemaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracionSistemaAllPropertiesEquals(ConfiguracionSistema expected, ConfiguracionSistema actual) {
        assertConfiguracionSistemaAutoGeneratedPropertiesEquals(expected, actual);
        assertConfiguracionSistemaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracionSistemaAllUpdatablePropertiesEquals(ConfiguracionSistema expected, ConfiguracionSistema actual) {
        assertConfiguracionSistemaUpdatableFieldsEquals(expected, actual);
        assertConfiguracionSistemaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracionSistemaAutoGeneratedPropertiesEquals(ConfiguracionSistema expected, ConfiguracionSistema actual) {
        assertThat(actual)
            .as("Verify ConfiguracionSistema auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracionSistemaUpdatableFieldsEquals(ConfiguracionSistema expected, ConfiguracionSistema actual) {
        assertThat(actual)
            .as("Verify ConfiguracionSistema relevant properties")
            .satisfies(a -> assertThat(a.getClave()).as("check clave").isEqualTo(expected.getClave()))
            .satisfies(a -> assertThat(a.getValor()).as("check valor").isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracionSistemaUpdatableRelationshipsEquals(ConfiguracionSistema expected, ConfiguracionSistema actual) {
        assertThat(actual)
            .as("Verify ConfiguracionSistema relationships")
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()));
    }
}
