package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstadoHabitacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoHabitacionAllPropertiesEquals(EstadoHabitacion expected, EstadoHabitacion actual) {
        assertEstadoHabitacionAutoGeneratedPropertiesEquals(expected, actual);
        assertEstadoHabitacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoHabitacionAllUpdatablePropertiesEquals(EstadoHabitacion expected, EstadoHabitacion actual) {
        assertEstadoHabitacionUpdatableFieldsEquals(expected, actual);
        assertEstadoHabitacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoHabitacionAutoGeneratedPropertiesEquals(EstadoHabitacion expected, EstadoHabitacion actual) {
        assertThat(actual)
            .as("Verify EstadoHabitacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoHabitacionUpdatableFieldsEquals(EstadoHabitacion expected, EstadoHabitacion actual) {
        assertThat(actual)
            .as("Verify EstadoHabitacion relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoHabitacionUpdatableRelationshipsEquals(EstadoHabitacion expected, EstadoHabitacion actual) {
        // empty method
    }
}
