package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HabitacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabitacionAllPropertiesEquals(Habitacion expected, Habitacion actual) {
        assertHabitacionAutoGeneratedPropertiesEquals(expected, actual);
        assertHabitacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabitacionAllUpdatablePropertiesEquals(Habitacion expected, Habitacion actual) {
        assertHabitacionUpdatableFieldsEquals(expected, actual);
        assertHabitacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabitacionAutoGeneratedPropertiesEquals(Habitacion expected, Habitacion actual) {
        assertThat(actual)
            .as("Verify Habitacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabitacionUpdatableFieldsEquals(Habitacion expected, Habitacion actual) {
        assertThat(actual)
            .as("Verify Habitacion relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getCapacidad()).as("check capacidad").isEqualTo(expected.getCapacidad()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHabitacionUpdatableRelationshipsEquals(Habitacion expected, Habitacion actual) {
        assertThat(actual)
            .as("Verify Habitacion relationships")
            .satisfies(a ->
                assertThat(a.getCategoriaHabitacion()).as("check categoriaHabitacion").isEqualTo(expected.getCategoriaHabitacion())
            )
            .satisfies(a -> assertThat(a.getEstadoHabitacion()).as("check estadoHabitacion").isEqualTo(expected.getEstadoHabitacion()));
    }
}
