package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImagenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagenAllPropertiesEquals(Imagen expected, Imagen actual) {
        assertImagenAutoGeneratedPropertiesEquals(expected, actual);
        assertImagenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagenAllUpdatablePropertiesEquals(Imagen expected, Imagen actual) {
        assertImagenUpdatableFieldsEquals(expected, actual);
        assertImagenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagenAutoGeneratedPropertiesEquals(Imagen expected, Imagen actual) {
        assertThat(actual)
            .as("Verify Imagen auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagenUpdatableFieldsEquals(Imagen expected, Imagen actual) {
        assertThat(actual)
            .as("Verify Imagen relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFichero()).as("check fichero").isEqualTo(expected.getFichero()))
            .satisfies(a ->
                assertThat(a.getFicheroContentType()).as("check fichero contenty type").isEqualTo(expected.getFicheroContentType())
            )
            .satisfies(a -> assertThat(a.getNombreArchivo()).as("check nombreArchivo").isEqualTo(expected.getNombreArchivo()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagenUpdatableRelationshipsEquals(Imagen expected, Imagen actual) {
        assertThat(actual)
            .as("Verify Imagen relationships")
            .satisfies(a -> assertThat(a.getHabitacion()).as("check habitacion").isEqualTo(expected.getHabitacion()))
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
