package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MensajeSoporteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeSoporteAllPropertiesEquals(MensajeSoporte expected, MensajeSoporte actual) {
        assertMensajeSoporteAutoGeneratedPropertiesEquals(expected, actual);
        assertMensajeSoporteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeSoporteAllUpdatablePropertiesEquals(MensajeSoporte expected, MensajeSoporte actual) {
        assertMensajeSoporteUpdatableFieldsEquals(expected, actual);
        assertMensajeSoporteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeSoporteAutoGeneratedPropertiesEquals(MensajeSoporte expected, MensajeSoporte actual) {
        assertThat(actual)
            .as("Verify MensajeSoporte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeSoporteUpdatableFieldsEquals(MensajeSoporte expected, MensajeSoporte actual) {
        assertThat(actual)
            .as("Verify MensajeSoporte relevant properties")
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getFechaMensaje()).as("check fechaMensaje").isEqualTo(expected.getFechaMensaje()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getUserName()).as("check userName").isEqualTo(expected.getUserName()))
            .satisfies(a -> assertThat(a.getLeido()).as("check leido").isEqualTo(expected.getLeido()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeSoporteUpdatableRelationshipsEquals(MensajeSoporte expected, MensajeSoporte actual) {
        assertThat(actual)
            .as("Verify MensajeSoporte relationships")
            .satisfies(a -> assertThat(a.getReserva()).as("check reserva").isEqualTo(expected.getReserva()));
    }
}
