package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedSociallandingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSociallandingAllPropertiesEquals(RedSociallanding expected, RedSociallanding actual) {
        assertRedSociallandingAutoGeneratedPropertiesEquals(expected, actual);
        assertRedSociallandingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSociallandingAllUpdatablePropertiesEquals(RedSociallanding expected, RedSociallanding actual) {
        assertRedSociallandingUpdatableFieldsEquals(expected, actual);
        assertRedSociallandingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSociallandingAutoGeneratedPropertiesEquals(RedSociallanding expected, RedSociallanding actual) {
        assertThat(actual)
            .as("Verify RedSociallanding auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSociallandingUpdatableFieldsEquals(RedSociallanding expected, RedSociallanding actual) {
        assertThat(actual)
            .as("Verify RedSociallanding relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getUrlEnlace()).as("check urlEnlace").isEqualTo(expected.getUrlEnlace()))
            .satisfies(a -> assertThat(a.getIconoUrl()).as("check iconoUrl").isEqualTo(expected.getIconoUrl()))
            .satisfies(a -> assertThat(a.getColorHex()).as("check colorHex").isEqualTo(expected.getColorHex()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSociallandingUpdatableRelationshipsEquals(RedSociallanding expected, RedSociallanding actual) {
        // empty method
    }
}
