package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedSocialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSocialAllPropertiesEquals(RedSocial expected, RedSocial actual) {
        assertRedSocialAutoGeneratedPropertiesEquals(expected, actual);
        assertRedSocialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSocialAllUpdatablePropertiesEquals(RedSocial expected, RedSocial actual) {
        assertRedSocialUpdatableFieldsEquals(expected, actual);
        assertRedSocialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSocialAutoGeneratedPropertiesEquals(RedSocial expected, RedSocial actual) {
        assertThat(actual)
            .as("Verify RedSocial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSocialUpdatableFieldsEquals(RedSocial expected, RedSocial actual) {
        assertThat(actual)
            .as("Verify RedSocial relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getUrlEnlace()).as("check urlEnlace").isEqualTo(expected.getUrlEnlace()))
            .satisfies(a -> assertThat(a.getIconoUrl()).as("check iconoUrl").isEqualTo(expected.getIconoUrl()))
            .satisfies(a -> assertThat(a.getColorHex()).as("check colorHex").isEqualTo(expected.getColorHex()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedSocialUpdatableRelationshipsEquals(RedSocial expected, RedSocial actual) {
        // empty method
    }
}
