package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservaDetalleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaDetalleAllPropertiesEquals(ReservaDetalle expected, ReservaDetalle actual) {
        assertReservaDetalleAutoGeneratedPropertiesEquals(expected, actual);
        assertReservaDetalleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaDetalleAllUpdatablePropertiesEquals(ReservaDetalle expected, ReservaDetalle actual) {
        assertReservaDetalleUpdatableFieldsEquals(expected, actual);
        assertReservaDetalleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaDetalleAutoGeneratedPropertiesEquals(ReservaDetalle expected, ReservaDetalle actual) {
        assertThat(actual)
            .as("Verify ReservaDetalle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaDetalleUpdatableFieldsEquals(ReservaDetalle expected, ReservaDetalle actual) {
        assertThat(actual)
            .as("Verify ReservaDetalle relevant properties")
            .satisfies(a -> assertThat(a.getNota()).as("check nota").isEqualTo(expected.getNota()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservaDetalleUpdatableRelationshipsEquals(ReservaDetalle expected, ReservaDetalle actual) {
        assertThat(actual)
            .as("Verify ReservaDetalle relationships")
            .satisfies(a -> assertThat(a.getReserva()).as("check reserva").isEqualTo(expected.getReserva()))
            .satisfies(a -> assertThat(a.getHabitacion()).as("check habitacion").isEqualTo(expected.getHabitacion()));
    }
}
