package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeccionContactoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionContactoAllPropertiesEquals(SeccionContacto expected, SeccionContacto actual) {
        assertSeccionContactoAutoGeneratedPropertiesEquals(expected, actual);
        assertSeccionContactoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionContactoAllUpdatablePropertiesEquals(SeccionContacto expected, SeccionContacto actual) {
        assertSeccionContactoUpdatableFieldsEquals(expected, actual);
        assertSeccionContactoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionContactoAutoGeneratedPropertiesEquals(SeccionContacto expected, SeccionContacto actual) {
        assertThat(actual)
            .as("Verify SeccionContacto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionContactoUpdatableFieldsEquals(SeccionContacto expected, SeccionContacto actual) {
        assertThat(actual)
            .as("Verify SeccionContacto relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getImagenFondoUrl()).as("check imagenFondoUrl").isEqualTo(expected.getImagenFondoUrl()))
            .satisfies(a -> assertThat(a.getCorreo()).as("check correo").isEqualTo(expected.getCorreo()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionContactoUpdatableRelationshipsEquals(SeccionContacto expected, SeccionContacto actual) {
        // empty method
    }
}
