package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeccionHeroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionHeroAllPropertiesEquals(SeccionHero expected, SeccionHero actual) {
        assertSeccionHeroAutoGeneratedPropertiesEquals(expected, actual);
        assertSeccionHeroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionHeroAllUpdatablePropertiesEquals(SeccionHero expected, SeccionHero actual) {
        assertSeccionHeroUpdatableFieldsEquals(expected, actual);
        assertSeccionHeroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionHeroAutoGeneratedPropertiesEquals(SeccionHero expected, SeccionHero actual) {
        assertThat(actual)
            .as("Verify SeccionHero auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionHeroUpdatableFieldsEquals(SeccionHero expected, SeccionHero actual) {
        assertThat(actual)
            .as("Verify SeccionHero relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getImagenFondoUrl()).as("check imagenFondoUrl").isEqualTo(expected.getImagenFondoUrl()))
            .satisfies(a -> assertThat(a.getTextoBoton()).as("check textoBoton").isEqualTo(expected.getTextoBoton()))
            .satisfies(a -> assertThat(a.getEnlaceBoton()).as("check enlaceBoton").isEqualTo(expected.getEnlaceBoton()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeccionHeroUpdatableRelationshipsEquals(SeccionHero expected, SeccionHero actual) {
        // empty method
    }
}
