package com.hotel.app.domain;

import static com.hotel.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServicioContratadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioContratadoAllPropertiesEquals(ServicioContratado expected, ServicioContratado actual) {
        assertServicioContratadoAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioContratadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioContratadoAllUpdatablePropertiesEquals(ServicioContratado expected, ServicioContratado actual) {
        assertServicioContratadoUpdatableFieldsEquals(expected, actual);
        assertServicioContratadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioContratadoAutoGeneratedPropertiesEquals(ServicioContratado expected, ServicioContratado actual) {
        assertThat(actual)
            .as("Verify ServicioContratado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioContratadoUpdatableFieldsEquals(ServicioContratado expected, ServicioContratado actual) {
        assertThat(actual)
            .as("Verify ServicioContratado relevant properties")
            .satisfies(a -> assertThat(a.getFechaContratacion()).as("check fechaContratacion").isEqualTo(expected.getFechaContratacion()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioContratadoUpdatableRelationshipsEquals(ServicioContratado expected, ServicioContratado actual) {
        assertThat(actual)
            .as("Verify ServicioContratado relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()))
            .satisfies(a -> assertThat(a.getReserva()).as("check reserva").isEqualTo(expected.getReserva()))
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getPago()).as("check pago").isEqualTo(expected.getPago()));
    }
}
