package com.hotel.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TelefonoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefonoAllPropertiesEquals(Telefono expected, Telefono actual) {
        assertTelefonoAutoGeneratedPropertiesEquals(expected, actual);
        assertTelefonoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefonoAllUpdatablePropertiesEquals(Telefono expected, Telefono actual) {
        assertTelefonoUpdatableFieldsEquals(expected, actual);
        assertTelefonoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefonoAutoGeneratedPropertiesEquals(Telefono expected, Telefono actual) {
        assertThat(actual)
            .as("Verify Telefono auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefonoUpdatableFieldsEquals(Telefono expected, Telefono actual) {
        assertThat(actual)
            .as("Verify Telefono relevant properties")
            .satisfies(a -> assertThat(a.getNumeroTel()).as("check numeroTel").isEqualTo(expected.getNumeroTel()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefonoUpdatableRelationshipsEquals(Telefono expected, Telefono actual) {
        // empty method
    }
}
